compiler_type = "ido"

[preserve_macros]
"ASSET_.*" = "unsigned int"
"g[DS]P.*" = "void"
"gs[DS]P.*" = "void"
"gDma.*" = "void"
"gDkr.*" = "void"
"fast3d_cmd" = "void"
"OS_PHYSICAL_TO_K0" = "void *"
"_SHIFTL" = "unsigned int"
"G_IM.*" = "unsigned int"
"KEEPLINEBREAK" = "void"
"IO_READ" = "volatile unsigned int *"
"WAIT_ON_IOBUSY" = "void"
"TEX_FORMAT_.*" = "unsigned int"
"G_TX_.*" = "unsigned int"
"TRUE" = "unsigned int"
"FALSE" = "unsigned int"
"NULL" = "unsigned int"
"G_CC.*" = "unsigned int"
"G_AC.*" = "unsigned int"
"ARRAY_COUNT" = "unsigned int"
"SCREEN_.*" = "unsigned int"
"TV_TYPE_.*" = "unsigned int"

[decompme.compilers]
"tools/ido-static-recomp/build/5.3/out/cc" = "ido5.3"
